### ISSUE TITLE
Errorcode starting app: -1

### ISSUE THREAD

**Issue by blee264** [zoeyjodon/moonlight-N3DS#15] opened 2024-03-15 04:41 UTC
This error shows on launching any of the games that are available in the moonlight app (the list fetched from the PC). Running GeForce Experience with latest graphics drivers.![image](https://github.com/zoeyjodon/moonlight-N3DS/assets/69402775/15d86e34-7d68-454e-a8ff-2932d0535f17)

**Comment by mikeyoung83** [comment] 2024-03-15 14:06
Same "-1" error for me when trying to connect to Sunshine
![20240315_100418](https://github.com/zoeyjodon/moonlight-N3DS/assets/8793989/3a5e73a9-142a-485c-8cc9-5d12a40669f9)

**Comment by RoblKyogre** [comment] 2024-03-15 17:31
unsure about geforce now, but think i remember getting this error for sunshine as well
fixed it by updating the moonlight-common-c module and compiling a new build, I think the fix is currently in the `enable-3d` branch atm
you could also fix it by downgrading sunshine to v0.21.0 in the meantime

**Comment by blee264** [comment] 2024-03-15 17:40
@mikeyoung83 your error is a bit different from mine. Based on the wording it looks like yours is having the connection terminated while mine is failing to launch the app maybe? It may be worth making a new issue. 

@RoblKyogre Do you remember whether your error was more like his or mine?

**Comment by mikeyoung83** [comment] 2024-03-15 17:47
@blee264 hmm yeah you're right. Sorry about that. I saw the "-1" error and just went ahead with commenting. But yes, I get as far as seeing the viewing options after connecting "big picture mode / desktop", and then I get the error above after selecting.

**Comment by zoeyjodon** [comment] 2024-03-16 16:31
> unsure about geforce now, but think I remember getting this error for sunshine as well fixed it by updating the moonlight-common-c module and compiling a new build, I think the fix is currently in the `enable-3d` branch atm you could also fix it by downgrading sunshine to v0.21.0 in the meantime

Can confirm, I just pushed an update to the moonlight-common-c module in the enable-3d branch that fixed the sunshine connection issue for me. Not sure if it will also fix the geforce crash though, since I haven't been able to reproduce that one.

**Comment by blee264** [comment] 2024-03-16 23:41
@zoeyjodon Do I need to compile to test if this fixes it for GeForce experience or should I wait for a new release?

It might take me a bit to figure out how to compile 😬

**Comment by RoblKyogre** [comment] 2024-03-16 23:48
> @zoeyjodon Do I need to compile to test if this fixes it for GeForce experience or should I wait for a new release?
> 
> It might take me a bit to figure out how to compile 😬

there should be a compiled build for that branch as an artifact in the Actions tab, here's a link to that: https://github.com/zoeyjodon/moonlight-N3DS/actions/runs/8310352245

**Comment by blee264** [comment] 2024-03-17 12:39
I just switched to Sunshine. I needed to stop dragging my feet on the change anyway. That build is working for me with the latest version of sunshine. 

Thanks, @RoblKyogre ! I had no idea you could get test builds that way!

**Comment by blee264** [comment] 2024-03-17 20:43
> @blee264 hmm yeah you're right. Sorry about that. I saw the "-1" error and just went ahead with commenting. But yes, I get as far as seeing the viewing options after connecting "big picture mode / desktop", and then I get the error above after selecting.

@mikeyoung83 no worries! Honestly, GeForce experience is phasing out support for game streaming anyway so your issue is probably more important for the software anyway. And it seems like the build that has an updated moonlight core fixes it!

**Comment by DanHolli** [comment] 2024-03-19 12:20
tested out the 3d build, no issues with it here (using latest Sunshine) and pretty cool too
looking forward to it getting merged into main 🤞

**Comment by zoeyjodon** [comment] 2024-03-23 11:51
Closing this now that I've released the fix!

**Closed by zoeyjodon** 2024-03-23 11:51 UTC
