### ISSUE TITLE
Connecting to the latest version of Sunshine crashes the console

### ISSUE THREAD

**Issue by amberdambey** [zoeyjodon/moonlight-N3DS#30] opened 2024-04-13 19:07 UTC
I'm using the New3DS-XL model running the latest official Nintendo firmware (11.17.0-50) and with the latest Luma3ds version (13.0.2). I tried this homebrew with my Windows 8.1 PC running an older version of Sunshine (unknown which one). It works fine aside from a color issue which was easily fixed by changing the width from 400 to 800. I try connecting it to my Linux PC (which I am able to connect to through my Steam Deck via Moonlight) which has Sunshine 0.23.0 and Moonlight-3DS crashes the whole system. All of the settings are left at default on both instances of Sunshine. The crash screen only shows once I've already paired _and_ entered the PIN in Sunshine. It crashes shortly after the IP address is selected from the first menu, specifically while displaying "Connecting to 172.16.0.11..."

**To Reproduce**
Explained in paragraph above

**Expected behavior**
Don't crash

**Screenshots**
Here's the screenshot of the crash screen as well as Luma3ds's crash dump.
![img_4149](https://github.com/zoeyjodon/moonlight-N3DS/assets/99459304/3ff72e8b-dcad-4c83-b1aa-e44e496eab95)
[crash_dump_00000009.dmp](https://github.com/zoeyjodon/moonlight-N3DS/files/14968399/crash_dump_00000009.dmp)

**Desktop (please complete the following information):**
 - OS: Arch Linux 2023.09.01 amd64
 - Sunshine v0.23.0
 - CPU is an AMD Ryzen with unknown specifications (clocked at 2.8 GHz and has at least 6 threads, but I have no way of definitively proving either)
 - GPU is an AMD Radeon RX Vega 11

**Additional context**
Everything relevant is included above. If more info is requested, I will provide it. Thanks.

**Comment by amberdambey** [comment] 2024-04-13 19:08
I realize this is a duplicate of #24. Closing.

**Comment by zoeyjodon** [comment] 2024-04-26 21:56
Not sure why this was reopened, since it _does_ look like a duplicate of the N3DS crash ticket. I'm gonna mark this as closed again.

**Closed by zoeyjodon** 2024-04-26 21:56 UTC
Labels: bug
